# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "ehci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aac735bb-816e-4cfe-be0b-175d120b3351";
    fsType = "ext4";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/5db69880-f5ed-4255-9884-33e9e416039b"; }];

  nix.maxJobs = lib.mkDefault 4;
}
