subnets:
    guest0:
        ipv4_prefix: ENC[AES256_GCM,data:xIE2werHlhsd,iv:SDhnUiUubfGovm7ckJIO2Ja0pECCth87rNolwY7zSyQ=,tag:iRw97Zwq0eCffJFdFLxdDQ==,type:str]
        ula_prefix: ENC[AES256_GCM,data:EdyI4REikQ9RXkWH0O2Ssw==,iv:sCenUC5k1Lzi2sYPrccO25J8R3OCwRzO8Gu6ZevbnsM=,tag:gsvUBr3i9721DBlXeOvhUg==,type:str]
        gua_prefix: ENC[AES256_GCM,data:R9uxckbE4sYLULiOdsVqo4uB2w==,iv:/UfOSIxmnJRNS9CSHRGN/875ZGhMEKAUxmaXWI6uKGw=,tag:1UjE5MMcdnsUfyIYQdrS/g==,type:str]
    iot0:
        ipv4_prefix: ENC[AES256_GCM,data:S2ETNcuktbW72w==,iv:fMUOOjoFswi2CaEBWCVJ0AQxZv0rq4M9WNt6zOfxSwk=,tag:gcjxMHJSYG82WzL1wpB+1Q==,type:str]
        ula_prefix: ENC[AES256_GCM,data:aMFmcV+VF/lbI+pRFJC7nSs=,iv:hjxvbzNuZUqcWU8o1M47rzeh3+TOQXR1kSSpwDgW1TI=,tag:pDQarurY0j13KQdzhQFL5A==,type:str]
        gua_prefix: ENC[AES256_GCM,data:OXVMu2YQGedr6QD6S0EKmW7lbA==,iv:g1NYhe9SxjJe0NP5OsKdsFBVXjSAKoqMF0zXcppLEg8=,tag:9FAJLNwtPaNLjPLiFutGDw==,type:str]
    lan0:
        ipv4_prefix: ENC[AES256_GCM,data:QkrY7FJUujNe1Q==,iv:j2yHTkHTvmtDOXNPmE6arxFwTU/eprxJ9GSeKlxI7PU=,tag:s7Me3NQp8q8OmZHuGrrT/A==,type:str]
        ula_prefix: ENC[AES256_GCM,data:sa70PSRInfogElOWk5AgIeQ=,iv:RU34ZnKH6OXLy0Ac+lESfqvekPBhAyUPUBBLDHCOYxA=,tag:wEs5l4FBYgd+UzpIIkI6vw==,type:str]
        gua_prefix: ENC[AES256_GCM,data:y2L4WJsFc59P2yaVDu81+lVmnQ==,iv:N4qApUsDHybGQeT2lWuOtexu2S1uVLUc+r9SAFBVH6U=,tag:KCryZpTzYEZKBMVaHpPP1Q==,type:str]
    mgmt0:
        ipv4_prefix: ENC[AES256_GCM,data:vBtApYVfV7WU,iv:6NuXD3Z4+BS91LDnPqkYZJRZKyA3fRxCmFXhVvMt/lw=,tag:kWnBniexYcSA+YZWyyG61Q==,type:str]
        ula_prefix: ENC[AES256_GCM,data:aw3E1tDJSmQ0PG537hf/nQ==,iv:Ial07gw7ZSo5BbLu7sIhB7QRQLowWW+iOlfmNIZDIzM=,tag:QkISbfMgo/AmMTwzywk8yQ==,type:str]
        gua_prefix: ENC[AES256_GCM,data:p2ZeUnmNOtVgdtGZJs6IE8/4ow==,iv:7+7xRtiAv5peoyKcqcAREeyGk6pw+bUylrliTG78w4o=,tag:P8771SIV3fXmJBizQSjgpQ==,type:str]
    dev0:
        ipv4_prefix: ENC[AES256_GCM,data:jL6wD2iZp8DgMg==,iv:KiSxVKE6BRdM/w3zpqe4n37v9RQ890nrQ8viQ2sTc2c=,tag:HAT50ajlagB6+8uSsfi/vQ==,type:str]
        ula_prefix: ENC[AES256_GCM,data:nX2TIUwqK2n2mBbfiVbwD4o=,iv:hHbIjJhzcD1eUfS+FJs+Wzovv6RICnNv/jVDLZaCbjc=,tag:A20/lGS4MonWzu2B9pBl0A==,type:str]
        gua_prefix: ENC[AES256_GCM,data:cfoTKtkdDOUvz1OJbRO3DjCrxg==,iv:M/0JLTQM6LH3BDplMEhRnvaP8tqlVJsfl6Tt958YkbA=,tag:I4C/ertORT9acpDshOPjeA==,type:str]
hosts:
    keylight:
        mac: ENC[AES256_GCM,data:YiWM3FL0B+JM11IDbNvHJ6Q=,iv:m03UCFh0NAZCJBirn4K2tsJrp9e0u8riahmo9LUw2PU=,tag:weyAi1LcXssOfTwCq9OecA==,type:str]
        ipv4: ENC[AES256_GCM,data:jvsrFAGTc0GU7wPa7Q==,iv:qXw6ri7NWZuWxEkKbZtYI6h29iTyLOStDy8xcKe730k=,tag:IGQSVWtDLfv935jjDnrHTw==,type:str]
        iid: ENC[AES256_GCM,data:4ZPtqs1Cb3To8Pon/5UbbX212Q==,iv:Gv+KeU775Q3xcqQ56xXuE8zcDcYLxs5oTXoP019RBME=,tag:JSJb38uRhgqVaTxUJ7lFng==,type:str]
    living-room-hue-hub.iot:
        mac: ENC[AES256_GCM,data:fzAXh9c0v0g20lxYl9JetaU=,iv:K+MRXJTRLfDSrMxGUDOvLGq/1uY6EE+r5ZkFHhTKUPE=,tag:i4ZtRrR6qogXpaN8zjzH/Q==,type:str]
        ipv4: ENC[AES256_GCM,data:y2+eOBKLVtNTFyWMiw==,iv:m/GW9nCbWbnRai3ppxMuf9UK4BBolQK7vDrX+wt/8Go=,tag:vYpgzuah9NGDWDcfPzjJvA==,type:str]
        iid: ENC[AES256_GCM,data:RCSrsOEs4v6rFETIKBN3ExHkHQ==,iv:0IXL055LIINMJNmIxbTwJDb3KIPuD523+i+6NRZ2+1s=,tag:i/1RHO+IvfQQw4LVyzooQw==,type:str]
    living-room-myq-hub.iot:
        mac: ENC[AES256_GCM,data:JRkU7v11meEbDSxCQBcJnLY=,iv:Ucozvi4HMerLSNlObi2Y1ROjgtE2rV485YXz61KxV1g=,tag:RyYCvLjeDVZmDTCyxpj6+w==,type:str]
        ipv4: ENC[AES256_GCM,data:e1FUcT0A6KAKKjGP0g==,iv:vKgbZfAdch5RG50V1CApCfqMkHU6UAiB46UphIFuqvo=,tag:DInpmkcn46TW7uq36Hywhg==,type:str]
        iid: ENC[AES256_GCM,data:KhDAuJbvk8SOtMLfp086NAOHZA==,iv:DX1KEq3YTG1yfVvlFEG2HCOhnHxKqorLZ5mudmaciE8=,tag:o/iEWfn4/kaUh7n/SJgOdA==,type:str]
    office-printer.iot:
        mac: ENC[AES256_GCM,data:qUlR82u+nbTe+ldKz7WhIuY=,iv:NEqa07931M5kh4aAu7AOvBzh20/HguSfDEy1NjFDb+M=,tag:bXImXScHHHGBhSEHnNK2rw==,type:str]
        ipv4: ENC[AES256_GCM,data:WIVxKV071MzxW1465A==,iv:FJZBu8ez5cl1D0i9sGDm5tAR1R1P9GyeCRbhmL1zr4Y=,tag:cwErDG7YlkBi2/X1FpshjA==,type:str]
        iid: ENC[AES256_GCM,data:AnRunM9kVoGfiftCWx4y6DqT+Q==,iv:BV6DDzqmdLWYkBKsI4B9zlvCV7oOJj2hF6FixbSA0JU=,tag:akonCTJ6LZ/bIS9nlB4OBw==,type:str]
    prusa-core-one.iot:
        mac: ENC[AES256_GCM,data:R2TagY6+LLsv9Dz0ve9KCbM=,iv:pbufV0kTqOOuxfwnm4BQqYaZTPaqdrdMYKWSL61Qok8=,tag:6EVtOkDe0AAwXlW438KOKg==,type:str]
        ipv4: ENC[AES256_GCM,data:F5Y7VtoTK4UrB+t7diw=,iv:DUPJYx58+vXaiwrdAzt7kpIhzoIi9kV29fNLDXeHChA=,tag:cHursg1aUEAUNIDcoqpUAg==,type:str]
        iid: ENC[AES256_GCM,data:CJG+E47QQ5wTlJZSt7M9ChyyVg==,iv:fio/+kSge4dOc11Vbuxu/Dsrl2rxVj65a7Ra27j7Mmk=,tag:fCAN0N3HVdA/fkyQTFwSMg==,type:str]
    psframework:
        mac: ENC[AES256_GCM,data:pQ7EeuiM66nzsNI0qgCLywM=,iv:eU40b+7VWM6H6de4Ry6HW+rLQkqKp5e/DTojfVXIp0o=,tag:uAaNBO0AjjIgcKF8goiyYg==,type:str]
        ipv4: ENC[AES256_GCM,data:QVJWg0d7gzDESH0VPQ==,iv:vO8wc2Bj1FsfVtLW5WickWKb3P/+z54BZ0kjsmnarmI=,tag:L913G6Vw+caRlxhmHM5J7w==,type:str]
        iid: ENC[AES256_GCM,data:IhGnFjwbcTbBOCGdupt4wJqmoA==,iv:La0CpnxybHgHxvdf6C/Hg8pHSW7f4BlPRjr0YWihdi8=,tag:qypfvuP2wD9ZSJO31KYjYw==,type:str]
    matt-4:
        mac: ENC[AES256_GCM,data:hJmIYOkHWCT0x5QPKsgok2Y=,iv:n7BFpsRVHGnB7iGy+cIsc27xQ8J+Cg91SUNHl7M7cnU=,tag:ObGiIK51s8tN9DDBQ5dyaA==,type:str]
        ipv4: ENC[AES256_GCM,data:32hKnKG8lwo9/A1HhA==,iv:xS8i0QzWJ+3I+RoTqYGsdImrzCIuA0wFvH5i0krX5TU=,tag:+1J6g1jEMvIB51zaSI1ekw==,type:str]
        iid: ENC[AES256_GCM,data:5t/yLEg6Hl6eWnlRIAIBD8J4Kg==,iv:zIOkAgWB5vsYUWmtEZirUo0QldaBnypFwRKSvGhMFMw=,tag:cIveCHQu7kkC16F4jfRPjA==,type:str]
    theatnerr-2:
        mac: ENC[AES256_GCM,data:43H9UURh7/gQDMl8fCWYrFs=,iv:Ultl7rPVwTBQzvx1016C1qSaM3o344svcDAJSGPcwng=,tag:kSvl8VAw+9EhnbQFBWuovg==,type:str]
        ipv4: ENC[AES256_GCM,data:iaw/e4EzKriSV6xz6w==,iv:YQSiMGxsNc5zpA2+fiNdxcSEjfVD0Pf9JXDL6oPYwPI=,tag:CzrH8xEu1AtNBi+G3fhuzw==,type:str]
        iid: ENC[AES256_GCM,data:45+T+2sTJ6welvHS5X/8ibJQ,iv:TgV08yoVXN6ZLLv0VnHWLWtDLPjVxxBE2oomBNlT/34=,tag:3sI8HpoxtxTINLAJcRPYVQ==,type:str]
    servnerr-4:
        mac: ENC[AES256_GCM,data:60LTGtvDifexlt09zpOTKw4=,iv:fGi2JjIurMzfkgoa+w1+D0Ly3rEMrY0dfvl6FqN67lk=,tag:syP5wkMEaHxhxCKINzCz+w==,type:str]
        ipv4: ENC[AES256_GCM,data:7NKMejp6Fxj8PSVM,iv:DHXqEn5VX2+S2obXRXZyUV40toRzJJ2uYTjckcv/95A=,tag:eoWdCqV2Xrzs3cAb4EWZJA==,type:str]
        iid: ENC[AES256_GCM,data:kHNyzTL1+jc=,iv:zEhcImiV7QOdN6giOkoJstUCuVYTPbyF9vfeRdy6YdU=,tag:5hPQt7xNV7MaqtPbKs2z7A==,type:str]
    nerr-4:
        mac: ENC[AES256_GCM,data:8mlnewaY7OoQK7SAnyzaSC0=,iv:DVYib3VsaTTW8lPv1uN0Y5GtquJXMTX367fv23b3KDQ=,tag:Xaj9YwzhCnvyTcY3q3CJ0A==,type:str]
        ipv4: ENC[AES256_GCM,data:JVboQ/XHWA3BUrI=,iv:5Cv7DkyoF+pfvzms/gd84Mbb/Tu6FROHQoCJyy9Cmq0=,tag:GMeHqtSXT3xSl17vd3q7kA==,type:str]
        iid_ula: ENC[AES256_GCM,data:2a4u2S/q9mDKX10KB06DWK9S,iv:GxUI63mYJq+7PdkkcVgNxXuOB51n3dX/KCyaQS2wxA4=,tag:AXCVwnwE71G9Q+nBnsk9rA==,type:str]
        iid_gua: ENC[AES256_GCM,data:KJ59JmJQnBv+i5Nmc6mxZpLp8g==,iv:kN3afNhK32eWZoiKYhv9P783U2+taAHhofseTFIrGOo=,tag:rJ860UzxdeqfwJUITM2ruw==,type:str]
    monitnerr-1:
        mac: ENC[AES256_GCM,data:Bta2Qc/cRBGEkGXnD9G1eM4=,iv:zKYVqzlVJjjdz7v6jz36Cv6r1/tux1zFW1KNbWdqaN8=,tag:GFzIA8CkITsGKzMCtrtwUw==,type:str]
        ipv4: ENC[AES256_GCM,data:uj1Kg3V1EyDZjdM=,iv:7h+iyxKrloig7OD/6L7CVNn4JYolxbSNaEQLhKlrUKE=,tag:FdnkWcNMS5GkWzXeleoyIA==,type:str]
        iid: ENC[AES256_GCM,data:l8Pb90GmspOvDjI/RDg7aklNhQ==,iv:0AAIWz69x2p1XCGvXE6BBQnqVgPoaRxugulxpAFlybs=,tag:/puwKOQ15Xa2ANTNYZVFXA==,type:str]
    switch-core:
        mac: ENC[AES256_GCM,data:bJJ+F92sETIW7TB9Uh/iTIY=,iv:KNiYVBRO3Z8gsr0WE8KyrIQdVtZIH4QSbWGPFao75qw=,tag:YzT+m7F10v1rC+hYRjXU9A==,type:str]
        ipv4: ENC[AES256_GCM,data:kscgINaF2WlhBKM=,iv:ZuviGPM+GcsQlzzAEmTc+RbqjhVph69+DD4UrHJ/T/Q=,tag:j/h3hMZB5tbiUIU1Y6Ln3g==,type:str]
        iid: ENC[AES256_GCM,data:29Af4nVC5S/c/mhDnpEoo+hAYQ==,iv:7HD3J7p0DThTZMtA/1gmPaPltHhRbWgMX9iWe8qcFNE=,tag:ESlN0Sq0yUi6jcucitPqfA==,type:str]
    switch-livingroom:
        mac: ENC[AES256_GCM,data:LMWGy4SpUj/bmAw6BdwHr4o=,iv:WdRnt/aqOG1TN4eozmHw1TIRO/HgfDnLCnMegVHrnBk=,tag:G6SB9H5NJV9SgEopg2/bEQ==,type:str]
        ipv4: ENC[AES256_GCM,data:VW7lNfpjuwQfWZU=,iv:VsFTJutIw+9HsT9+ynNe/G2+GdWJm+c4FivDjVHftgs=,tag:wLgRhn1VpFzfmssAoj9gzw==,type:str]
        iid: ENC[AES256_GCM,data:DINZAbF+aUrhm1oUvYHgNhk+,iv:7TytCdbBQ0w/DtvOX1rMx6LDRXxcRsf71cyRRZJGL1Y=,tag:HGwkhw9b/eDgywlFG4L+pA==,type:str]
    switch-office:
        mac: ENC[AES256_GCM,data:FD6F47D/XSRm1hxl0PXgh7k=,iv:iC4rh1FMdXM/ZakMwm7xug4x0iuPtSIb8jBB7IBIayM=,tag:VI9fPHBdyeZoyX9++35+YQ==,type:str]
        ipv4: ENC[AES256_GCM,data:0H91Iv+132TX7aU=,iv:TIPhsIxLFOLDZjAYOoz1dJ1b76Dj33Hr6AyXJAg/kqA=,tag:kN1vtTecWJp/boE1Yt0kXA==,type:str]
        iid: ENC[AES256_GCM,data:Vr3xnG0SFhV6VNq3WAs14fwZKA==,iv:+psKrGrLIvdlusq87C9PQ97UphDWhdyEPP1AH5wqlX0=,tag:xnLT9MA12jhPk6MI0DdTTQ==,type:str]
    pdu01:
        mac: ENC[AES256_GCM,data:a26xGDnTICTOxoUmvxdAIro=,iv:5+4Pf2fM2FJ1n2WJKwEG6WLvQrs7clEFBJj+3aa/nJc=,tag:/0gK8oruITUMZOx25nTi+w==,type:str]
        ipv4: ENC[AES256_GCM,data:JItNN1ltdgMWW54=,iv:KrPOKUtgKjdejOwsVVkFaniA7Z2KDFnqoJ/ILoMz4cg=,tag:SZqklcA+qvKzgO4KYUbV2g==,type:str]
        iid: ENC[AES256_GCM,data:FJS4/5PURmkVe8ei/tr7ytU1,iv:a9qRn9abovvnbq8xW19b2xUlRsU9voxERW6RMMhdAac=,tag:vXXC9vpnwaQ4lcqYhZ/juQ==,type:str]
    ap-livingroom:
        mac: ENC[AES256_GCM,data:hb96HaengZHVdGfZMAU+9Sg=,iv:Skx/lwGoMMSA0MFazlqJkh88lc9Ccvb3iwkOhkQ5viQ=,tag:otfCvWZCd2QTJ3nETtTSlg==,type:str]
        ipv4: ENC[AES256_GCM,data:Pz2OTuZypxldlGw=,iv:Lu0LX7hyt2cRT6Urt2h5dnZOsvmC9nv1jp9ay0yTFUY=,tag:C0U5xTdDWDEUvNG3/fz1jA==,type:str]
        iid: ENC[AES256_GCM,data:MB5TxyIlgbzTOMiLwNveWS+JRQ==,iv:K3IrLMD9XYOpdhz3PoB5qOL4LwMzui1XwsY8u1/QgB0=,tag:4cmeD5uyTOIvBXwd+B5+6w==,type:str]
    ap-basement:
        mac: ENC[AES256_GCM,data:Ce8Qx2jXGvKu6VAK7EgMJrs=,iv:aq9yxJBhiATzLbWErNVDd1EDuptbJ+b90Te3qMamP9A=,tag:kdoEQkhbz1MKiHkyJOdBsg==,type:str]
        ipv4: ENC[AES256_GCM,data:LnziVPkVA2KMPZc=,iv:gKER+PQaFeyvw2lVVs3HVzL512JxJ3cJbg4d7221ewo=,tag:NtvVjRIYcybH3pMr1QRwDA==,type:str]
        iid: ENC[AES256_GCM,data:sVBTyqsTA7dwmZsBgQtitsZlZw==,iv:tfnLIkBby3GH/oalSxv+sCcKHrvaX2ySIy7lm3Z3ygs=,tag:H2ABMUElshO2kPrCftZYFA==,type:str]
    ups01:
        mac: ENC[AES256_GCM,data:mzwXMqDaf6qmVqSskfpxlCk=,iv:+rO+WzoH6hn+7EweVAQtNjGv3tkvbJl2Dd3wYwEgjX4=,tag:boQVaT+xN4l2+9JQTZiPFg==,type:str]
        ipv4: ENC[AES256_GCM,data:4cvJ7e1GgqgEfivb,iv:VM7uaB5vgoncVLaBVUt+rJx1iyi8gtFGK7eitBHI+NY=,tag:7xkgMKMpsC/JwYC5vBfLxg==,type:str]
        iid: ENC[AES256_GCM,data:/x2O9LTO3gPPH8jeUZqOAmp6,iv:x5oemCTGDtICSbPU698Z/lXm2w4Hcwc27L+fCA4VBYU=,tag:kf3hP9wwZc1QxIvS4YVmRA==,type:str]
    hass:
        mac: ENC[AES256_GCM,data:enEPXoX0QpCNTHGJ5DITJ1w=,iv:OBy/ivwqiHmIrXopRazmjRGPWaRiqPjAgvIFrnI8S1E=,tag:M089Ye+SDphcfGUCMtgFHg==,type:str]
        ipv4: ENC[AES256_GCM,data:ZIWb1cpXW4ToYj/E,iv:l9K2F49tGUCBm/dAZhoslVcDC9JgGd3HgEskBNxgK50=,tag:zuTGU23z1t8H2KIC+C7CvQ==,type:str]
        iid_ula: ENC[AES256_GCM,data:IW0pCePwtiqgsYf2qb4jNTKyIg==,iv:4+291WbrsQBlMEAi+sWfyqSRFX2PChKSbU2i5qmfLsU=,tag:aZ13AyKx4cSxE3cQ/PpTOQ==,type:str]
        iid_gua: ENC[AES256_GCM,data:dfrS8ugTKJDyOpXza8ABD5Ju+g==,iv:b2sfGigTnIe2eptsv9FMXVMQVHgYMv/0/hkbJRpNhAo=,tag:R/zhgtMcFjOetB7SOQoQMQ==,type:str]
    linuxdev:
        mac: ENC[AES256_GCM,data:lgqkkxH3gAzAWa8aUxly758=,iv:lAWuORjKF2DsM8VV2yy4s4/5Hqox6ULJ2149KY/B2m0=,tag:eS7OZEDZyrmdAcYHb5JvKQ==,type:str]
        ipv4: ENC[AES256_GCM,data:7BTOIL6gBmFFCxaZlQ==,iv:os8tMdCsTD8C0ZfdCAUqinhsfHQlOiEravjKoOGuo18=,tag:N4VX+aYXNrphdpYNpxHa0Q==,type:str]
        iid: ENC[AES256_GCM,data:uNDEPZWPJYQ=,iv:ELIlBFOhaP4i7kt3JIEC/h49VI9vrlEcBioOpflxnTA=,tag:H1/gWzcvjv2S+KF616uEug==,type:str]
site:
    ula_prefix: ENC[AES256_GCM,data:6T1bH4px3896aw0szcE=,iv:nMUC/Qxm20jd+2HDjrCd5Rm6PzPoFT7mjMigIjamWFQ=,tag:gEIMOlfgLkRkRm2ofUTIkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRHpPOHU3dVVDV0VWYlJI
            NTJDM1M2WUdVOVgzbnVWYmMray9IencyTGlzCmF6WXNNTWVUdzRrYXJjR0dRRVk4
            SVhSQ3FPdXE3eVM5eWxycXN2MXQ0V2MKLS0tIFdzeW10OVNMZzFHbHZUaGV0eW9D
            VzlEQUxwK1Z5ZWtHTXdDQitMZnF3eEEKRLda4Q1JbeQ+uDrw8C2Oe7G9oHWSpI+x
            iNDvynUfqhC78V4vBPQiwm+7PXXrKopDvh7PqMlmNTHDV6qTRN0YKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136z4kwkfsqlvaa7e6f5c79rzjstg4ktq2lw6zadv23c038jnafssp2mngs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR3Flb0lNcXBpeWJqRk1v
            aUFFVWhIZ3YrU0huVFhlM2J0N3RPRWF4aEV3CjhSOHJ5cGMvcmg4R1IrU2h1dTFy
            T0Vzb24vcXNNblBqcXhtT2JTZURucUkKLS0tIC9XQjdJREZFTEY3bGJQZVRmaG9t
            OVc3QlhhdEd4cmFIYWtXSENLN1RvUGsK9ZfsmSrbkgc36sI/G8HI1VQD810zUfI7
            0e6pYLkir7QL99bfpm9s+vAE2Mi9t0FtLbhqfyz2RU1NqCqHblqnEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgxvcs9q6zr4l8udgxgnzj02rzcqy4dt9x2gz9u2k97dnhj88pvqlhlvk8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaENHY0lZY0M4ZVNSdU53
            dDB0SjJpTnA2RytDdTkzVTNTZThsdzg1UmtBClhnRVNERURqcThGZTgzTVlMMW1E
            SzNyNnlUdGpCTVZsdTJZNHN1SENicncKLS0tIE5EdVRBaElCeDcyYWlRbWtmMjVT
            TUJVSWYrRm9HMCtFSGZyd0pGWm9qTmcKXqiTo8CZ/07GE/55FLaXqMduwWEVG59N
            cDPOfAk4laZPZFaHsxa5+cYlf7aXtAuDOfF3U/p6pvomp0gA0Ku67w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dt4928w6c2py0rzcnwntdr6dcf62mf8wkhe3hm8mnscqxcewrdkqz6jh3d
    lastmodified: "2026-08-30T14:43:11Z"
    mac: ENC[AES256_GCM,data:cteOykJcJsjJZF9CLSUyOs4QnPS+9e9tH97g4LfhxKcmlBRYUqvUdXnPQRlgld9HxUartBNT8KFllVs1q5xZGcaoK94FJ/FdVhMookdQYg2bwqlIjUQJcw+a5q74nEO3udxp68JZnwtSorh+4xBYWtgsj7hR//BAi97++EEJtpY=,iv:s+DLnsxMPruLqn2pzHTZO5irtLNwK3IcqBNhbK/uGb4=,tag:58Ztknhy6V/mecst7wgiTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
