subnets:
    guest0:
        ipv4_prefix: ENC[AES256_GCM,data:xIE2werHlhsd,iv:SDhnUiUubfGovm7ckJIO2Ja0pECCth87rNolwY7zSyQ=,tag:iRw97Zwq0eCffJFdFLxdDQ==,type:str]
        ula_prefix: ENC[AES256_GCM,data:AgbpHqkLbSNBBZRYoMd/nwxN,iv:gHSIk9ejeqJYgXBJEvk/R8QqRceJBXBTg5+wp6+GAJ0=,tag:C+3Hi4ZLKb0h7unxRgAtZw==,type:str]
        gua_prefix: ENC[AES256_GCM,data:R9uxckbE4sYLULiOdsVqo4uB2w==,iv:/UfOSIxmnJRNS9CSHRGN/875ZGhMEKAUxmaXWI6uKGw=,tag:1UjE5MMcdnsUfyIYQdrS/g==,type:str]
    iot0:
        ipv4_prefix: ENC[AES256_GCM,data:S2ETNcuktbW72w==,iv:fMUOOjoFswi2CaEBWCVJ0AQxZv0rq4M9WNt6zOfxSwk=,tag:gcjxMHJSYG82WzL1wpB+1Q==,type:str]
        ula_prefix: ENC[AES256_GCM,data:MExQA3eaPagQUlXCYleGMzhO,iv:hMkMHGAH0oonBd+uxdpAeLmG4Vz0fCmH5az0++EObe0=,tag:OKCB8dlwmHr2+yxXwZGx4g==,type:str]
        gua_prefix: ENC[AES256_GCM,data:OXVMu2YQGedr6QD6S0EKmW7lbA==,iv:g1NYhe9SxjJe0NP5OsKdsFBVXjSAKoqMF0zXcppLEg8=,tag:9FAJLNwtPaNLjPLiFutGDw==,type:str]
    lan0:
        ipv4_prefix: ENC[AES256_GCM,data:QkrY7FJUujNe1Q==,iv:j2yHTkHTvmtDOXNPmE6arxFwTU/eprxJ9GSeKlxI7PU=,tag:s7Me3NQp8q8OmZHuGrrT/A==,type:str]
        ula_prefix: ENC[AES256_GCM,data:y2QXrZzVavMIdfJsdUMiNyoM,iv:g7D3OB5L2rK/HhqJMgESveGvfe/wvNs7JL3yVW5+yUw=,tag:gRe6Ra+JD6sEQbnmAXxx+A==,type:str]
        gua_prefix: ENC[AES256_GCM,data:y2L4WJsFc59P2yaVDu81+lVmnQ==,iv:N4qApUsDHybGQeT2lWuOtexu2S1uVLUc+r9SAFBVH6U=,tag:KCryZpTzYEZKBMVaHpPP1Q==,type:str]
    mgmt0:
        ipv4_prefix: ENC[AES256_GCM,data:vBtApYVfV7WU,iv:6NuXD3Z4+BS91LDnPqkYZJRZKyA3fRxCmFXhVvMt/lw=,tag:kWnBniexYcSA+YZWyyG61Q==,type:str]
        ula_prefix: ENC[AES256_GCM,data:mvlqlNUekK7pPXLGnnGqBYhA,iv:dcIJ5dd8y2iO0ZURKd8p1+z0NaCP0EJ/KXAJ9PAFY5Q=,tag:Z9T3o6ZWovG6KFpvdPIYDA==,type:str]
        gua_prefix: ENC[AES256_GCM,data:p2ZeUnmNOtVgdtGZJs6IE8/4ow==,iv:7+7xRtiAv5peoyKcqcAREeyGk6pw+bUylrliTG78w4o=,tag:P8771SIV3fXmJBizQSjgpQ==,type:str]
    dev0:
        ipv4_prefix: ENC[AES256_GCM,data:jL6wD2iZp8DgMg==,iv:KiSxVKE6BRdM/w3zpqe4n37v9RQ890nrQ8viQ2sTc2c=,tag:HAT50ajlagB6+8uSsfi/vQ==,type:str]
        ula_prefix: ENC[AES256_GCM,data:M9/dtdA74ssjxW315oPBhCHw,iv:wtN2KA+Qj/VmxqNTKkd+rj2uBz8JEEz0TG0v3P0YpFI=,tag:VFKPzlwSfJongx78cU47Fg==,type:str]
        gua_prefix: ENC[AES256_GCM,data:cfoTKtkdDOUvz1OJbRO3DjCrxg==,iv:M/0JLTQM6LH3BDplMEhRnvaP8tqlVJsfl6Tt958YkbA=,tag:I4C/ertORT9acpDshOPjeA==,type:str]
hosts:
    keylight:
        mac: ENC[AES256_GCM,data:YiWM3FL0B+JM11IDbNvHJ6Q=,iv:m03UCFh0NAZCJBirn4K2tsJrp9e0u8riahmo9LUw2PU=,tag:weyAi1LcXssOfTwCq9OecA==,type:str]
        ipv4: ENC[AES256_GCM,data:+FWSU4GVkIgwGw==,iv:D3CJqjfPGfCl7IPbOcenkdS3n9rRYMCu8JsRLSbHyHk=,tag:xYarmVbdTXwcAR1A5wdpqQ==,type:str]
        iid: ENC[AES256_GCM,data:4ZPtqs1Cb3To8Pon/5UbbX212Q==,iv:Gv+KeU775Q3xcqQ56xXuE8zcDcYLxs5oTXoP019RBME=,tag:JSJb38uRhgqVaTxUJ7lFng==,type:str]
    living-room-hue-hub:
        mac: ENC[AES256_GCM,data:hfuAiWAPLbKuviqy4CmobeU=,iv:hkpeH+fzNx6fxg4zH8E3fOBxWDF9DIYP2HGaRO0C6BU=,tag:3MyfUf1gawW7ShA725LDGQ==,type:str]
        ipv4: ENC[AES256_GCM,data:wm1tigbWNFOaew==,iv:vkPnlKaRW+oIo5LYzgI4sGtylBUo07o150OMbAyqZqA=,tag:WVr3U4ImFq42iDCWPdSrvg==,type:str]
        iid: ENC[AES256_GCM,data:48iO93PyJmRxHjj621Opa9J9zw==,iv:z9Ri47SUMDggt5ILs/Q0RBAt40Em7pDSp8zyAsk3EVI=,tag:KVVBGXGRGika9uSqvnBupQ==,type:str]
    living-room-myq-hub:
        mac: ENC[AES256_GCM,data:6TXmbzPgt6UD8370JG3AteU=,iv:qiY1tELK52BfYUBZT3ds/YmGTyCgSGj9pYIcEyW+xds=,tag:4xvNQXDLWORiqEb9ssr+ig==,type:str]
        ipv4: ENC[AES256_GCM,data:vXMghlqTC9KacQ==,iv:zNYq2xwlhF+dKMCAhh9Tj3cd3GyebG1+dOkFZ8YRxZY=,tag:p/DVECONriZqVtOLmUhgaw==,type:str]
        iid: ENC[AES256_GCM,data:mhAzWSNv1DQh396Xxj2ttEraZQ==,iv:si6d+fzi6R/G9yu88cz2FD3MzA1hS0116RMhPCUbo+g=,tag:ISVTHTBVeqpdmxGMhgBZ/g==,type:str]
    office-printer:
        mac: ENC[AES256_GCM,data:m+3Dg0Cj0yMi/T+aRVO5wRY=,iv:ZnibnEVIYslkhb70zVvo4sh826hy0K/XDDBAWhL5Wa4=,tag:D6aK9fsE9vQEQcPb8oVSuw==,type:str]
        ipv4: ENC[AES256_GCM,data:jThucPjXAvu6iQ==,iv:2Ff+oFqIb0LtesBqW2cK5+jOpoB81gggjYzDs8rxn8E=,tag:cx/+b2/VorHaGNDRWkZACw==,type:str]
        iid: ENC[AES256_GCM,data:odwvScX2I7Qy1yCrmD3/dn6FOA==,iv:J6+uMz8pkal3Wto5bRz8MfmwHNh4s0xNTD6eBXVTNPA=,tag:LyKIchj6XzsHo0EP2A+tng==,type:str]
    prusa-core-one:
        mac: ENC[AES256_GCM,data:+L6pkdkly8mSLq5BctS8Xnw=,iv:qmtyWSPOOkPJGJ+33pxicIWvcTte/anMBXTjPNYMNDA=,tag:uZ/B4GocsbOOVKogoc+0mw==,type:str]
        ipv4: ENC[AES256_GCM,data:+XXC2z36XL8etMM=,iv:MVYKrKjzTJ/wVdvDvr/wxjzSSru8YswWa73gQdu6ksE=,tag:gzUM5JgH41hj4l8ONuxuYQ==,type:str]
        iid: ENC[AES256_GCM,data:VA/D0VplZvWBFtEqzPkSosdJ/g==,iv:WpqjWnN0RWAhicXJwb3otwvfER7i/odjvM5EgHY6X7U=,tag:d84yPuk5ow/rdEkzufN7yg==,type:str]
    psframework:
        mac: ENC[AES256_GCM,data:pQ7EeuiM66nzsNI0qgCLywM=,iv:eU40b+7VWM6H6de4Ry6HW+rLQkqKp5e/DTojfVXIp0o=,tag:uAaNBO0AjjIgcKF8goiyYg==,type:str]
        ipv4: ENC[AES256_GCM,data:Kx0UdHScHpf37w==,iv:g1Y29JlZJ68+DbNeoiOfs1XtGZwlOo/Shj8fy/t46SQ=,tag:1CsEhNVrpUnGsymgJRzB/Q==,type:str]
        iid: ENC[AES256_GCM,data:IhGnFjwbcTbBOCGdupt4wJqmoA==,iv:La0CpnxybHgHxvdf6C/Hg8pHSW7f4BlPRjr0YWihdi8=,tag:qypfvuP2wD9ZSJO31KYjYw==,type:str]
    matt-4:
        mac: ENC[AES256_GCM,data:hJmIYOkHWCT0x5QPKsgok2Y=,iv:n7BFpsRVHGnB7iGy+cIsc27xQ8J+Cg91SUNHl7M7cnU=,tag:ObGiIK51s8tN9DDBQ5dyaA==,type:str]
        ipv4: ENC[AES256_GCM,data:nG3QCDkQIi+SBg==,iv:+0nMEmNiGvrDagBGM3FMAS//h8m8OvQeAqKteoUy/IY=,tag:dE82KJwxBFM1ySgiWa5hhw==,type:str]
        iid: ENC[AES256_GCM,data:5t/yLEg6Hl6eWnlRIAIBD8J4Kg==,iv:zIOkAgWB5vsYUWmtEZirUo0QldaBnypFwRKSvGhMFMw=,tag:cIveCHQu7kkC16F4jfRPjA==,type:str]
    theatnerr-2:
        mac: ENC[AES256_GCM,data:43H9UURh7/gQDMl8fCWYrFs=,iv:Ultl7rPVwTBQzvx1016C1qSaM3o344svcDAJSGPcwng=,tag:kSvl8VAw+9EhnbQFBWuovg==,type:str]
        ipv4: ENC[AES256_GCM,data:uqZXyECq8k4drA==,iv:wmgpFn8Mv6WfUG06vT9p+weZs07fpdpM0LknTH19d6A=,tag:IGmK6GMsNTAZcuIOSp0GXQ==,type:str]
        iid: ENC[AES256_GCM,data:45+T+2sTJ6welvHS5X/8ibJQ,iv:TgV08yoVXN6ZLLv0VnHWLWtDLPjVxxBE2oomBNlT/34=,tag:3sI8HpoxtxTINLAJcRPYVQ==,type:str]
    servnerr-4:
        mac: ENC[AES256_GCM,data:60LTGtvDifexlt09zpOTKw4=,iv:fGi2JjIurMzfkgoa+w1+D0Ly3rEMrY0dfvl6FqN67lk=,tag:syP5wkMEaHxhxCKINzCz+w==,type:str]
        ipv4: ENC[AES256_GCM,data:7NKMejp6Fxj8PSVM,iv:DHXqEn5VX2+S2obXRXZyUV40toRzJJ2uYTjckcv/95A=,tag:eoWdCqV2Xrzs3cAb4EWZJA==,type:str]
        iid: ENC[AES256_GCM,data:kHNyzTL1+jc=,iv:zEhcImiV7QOdN6giOkoJstUCuVYTPbyF9vfeRdy6YdU=,tag:5hPQt7xNV7MaqtPbKs2z7A==,type:str]
    nerr-4:
        mac: ENC[AES256_GCM,data:8mlnewaY7OoQK7SAnyzaSC0=,iv:DVYib3VsaTTW8lPv1uN0Y5GtquJXMTX367fv23b3KDQ=,tag:Xaj9YwzhCnvyTcY3q3CJ0A==,type:str]
        ipv4: ENC[AES256_GCM,data:JVboQ/XHWA3BUrI=,iv:5Cv7DkyoF+pfvzms/gd84Mbb/Tu6FROHQoCJyy9Cmq0=,tag:GMeHqtSXT3xSl17vd3q7kA==,type:str]
        iid_ula: ENC[AES256_GCM,data:wZ9SWcm73ZtrCb1z4qW8vLztSw==,iv:MsR8t36EDDA6XIpKDuYSpVHKK4ytSOsX7KuoGbfKVaw=,tag:lQVnC+MMb/6FLN2nrFe9Sw==,type:str]
        iid_gua: ENC[AES256_GCM,data:KJ59JmJQnBv+i5Nmc6mxZpLp8g==,iv:kN3afNhK32eWZoiKYhv9P783U2+taAHhofseTFIrGOo=,tag:rJ860UzxdeqfwJUITM2ruw==,type:str]
    switch-core:
        mac: ENC[AES256_GCM,data:bJJ+F92sETIW7TB9Uh/iTIY=,iv:KNiYVBRO3Z8gsr0WE8KyrIQdVtZIH4QSbWGPFao75qw=,tag:YzT+m7F10v1rC+hYRjXU9A==,type:str]
        ipv4: ENC[AES256_GCM,data:kscgINaF2WlhBKM=,iv:ZuviGPM+GcsQlzzAEmTc+RbqjhVph69+DD4UrHJ/T/Q=,tag:j/h3hMZB5tbiUIU1Y6Ln3g==,type:str]
        iid: ENC[AES256_GCM,data:29Af4nVC5S/c/mhDnpEoo+hAYQ==,iv:7HD3J7p0DThTZMtA/1gmPaPltHhRbWgMX9iWe8qcFNE=,tag:ESlN0Sq0yUi6jcucitPqfA==,type:str]
    switch-livingroom:
        mac: ENC[AES256_GCM,data:LMWGy4SpUj/bmAw6BdwHr4o=,iv:WdRnt/aqOG1TN4eozmHw1TIRO/HgfDnLCnMegVHrnBk=,tag:G6SB9H5NJV9SgEopg2/bEQ==,type:str]
        ipv4: ENC[AES256_GCM,data:VW7lNfpjuwQfWZU=,iv:VsFTJutIw+9HsT9+ynNe/G2+GdWJm+c4FivDjVHftgs=,tag:wLgRhn1VpFzfmssAoj9gzw==,type:str]
        iid: ENC[AES256_GCM,data:DINZAbF+aUrhm1oUvYHgNhk+,iv:7TytCdbBQ0w/DtvOX1rMx6LDRXxcRsf71cyRRZJGL1Y=,tag:HGwkhw9b/eDgywlFG4L+pA==,type:str]
    pdu01:
        mac: ENC[AES256_GCM,data:a26xGDnTICTOxoUmvxdAIro=,iv:5+4Pf2fM2FJ1n2WJKwEG6WLvQrs7clEFBJj+3aa/nJc=,tag:/0gK8oruITUMZOx25nTi+w==,type:str]
        ipv4: ENC[AES256_GCM,data:JItNN1ltdgMWW54=,iv:KrPOKUtgKjdejOwsVVkFaniA7Z2KDFnqoJ/ILoMz4cg=,tag:SZqklcA+qvKzgO4KYUbV2g==,type:str]
        iid: ENC[AES256_GCM,data:FJS4/5PURmkVe8ei/tr7ytU1,iv:a9qRn9abovvnbq8xW19b2xUlRsU9voxERW6RMMhdAac=,tag:vXXC9vpnwaQ4lcqYhZ/juQ==,type:str]
    ap-livingroom:
        mac: ENC[AES256_GCM,data:hb96HaengZHVdGfZMAU+9Sg=,iv:Skx/lwGoMMSA0MFazlqJkh88lc9Ccvb3iwkOhkQ5viQ=,tag:otfCvWZCd2QTJ3nETtTSlg==,type:str]
        ipv4: ENC[AES256_GCM,data:Pz2OTuZypxldlGw=,iv:Lu0LX7hyt2cRT6Urt2h5dnZOsvmC9nv1jp9ay0yTFUY=,tag:C0U5xTdDWDEUvNG3/fz1jA==,type:str]
        iid: ENC[AES256_GCM,data:MB5TxyIlgbzTOMiLwNveWS+JRQ==,iv:K3IrLMD9XYOpdhz3PoB5qOL4LwMzui1XwsY8u1/QgB0=,tag:4cmeD5uyTOIvBXwd+B5+6w==,type:str]
    ap-basement:
        mac: ENC[AES256_GCM,data:Ce8Qx2jXGvKu6VAK7EgMJrs=,iv:aq9yxJBhiATzLbWErNVDd1EDuptbJ+b90Te3qMamP9A=,tag:kdoEQkhbz1MKiHkyJOdBsg==,type:str]
        ipv4: ENC[AES256_GCM,data:LnziVPkVA2KMPZc=,iv:gKER+PQaFeyvw2lVVs3HVzL512JxJ3cJbg4d7221ewo=,tag:NtvVjRIYcybH3pMr1QRwDA==,type:str]
        iid: ENC[AES256_GCM,data:sVBTyqsTA7dwmZsBgQtitsZlZw==,iv:tfnLIkBby3GH/oalSxv+sCcKHrvaX2ySIy7lm3Z3ygs=,tag:H2ABMUElshO2kPrCftZYFA==,type:str]
    ups01:
        mac: ENC[AES256_GCM,data:mzwXMqDaf6qmVqSskfpxlCk=,iv:+rO+WzoH6hn+7EweVAQtNjGv3tkvbJl2Dd3wYwEgjX4=,tag:boQVaT+xN4l2+9JQTZiPFg==,type:str]
        ipv4: ENC[AES256_GCM,data:4cvJ7e1GgqgEfivb,iv:VM7uaB5vgoncVLaBVUt+rJx1iyi8gtFGK7eitBHI+NY=,tag:7xkgMKMpsC/JwYC5vBfLxg==,type:str]
        iid: ENC[AES256_GCM,data:/x2O9LTO3gPPH8jeUZqOAmp6,iv:x5oemCTGDtICSbPU698Z/lXm2w4Hcwc27L+fCA4VBYU=,tag:kf3hP9wwZc1QxIvS4YVmRA==,type:str]
    hass:
        mac: ENC[AES256_GCM,data:enEPXoX0QpCNTHGJ5DITJ1w=,iv:OBy/ivwqiHmIrXopRazmjRGPWaRiqPjAgvIFrnI8S1E=,tag:M089Ye+SDphcfGUCMtgFHg==,type:str]
        ipv4: ENC[AES256_GCM,data:ZIWb1cpXW4ToYj/E,iv:l9K2F49tGUCBm/dAZhoslVcDC9JgGd3HgEskBNxgK50=,tag:zuTGU23z1t8H2KIC+C7CvQ==,type:str]
        iid_ula: ENC[AES256_GCM,data:fKDR5jyi1IBpF7Ru8xikXDRVeQ==,iv:QoRzhIUmT7qVs4COaiaoR8rmkYB0s3ZIpqHoCLWvWLM=,tag:JPDUM6XNZBhmlCR7qUzU6g==,type:str]
        iid_gua: ENC[AES256_GCM,data:dfrS8ugTKJDyOpXza8ABD5Ju+g==,iv:b2sfGigTnIe2eptsv9FMXVMQVHgYMv/0/hkbJRpNhAo=,tag:R/zhgtMcFjOetB7SOQoQMQ==,type:str]
    linuxdev:
        mac: ENC[AES256_GCM,data:ejquyCNlfbUvrNxsJKD356s=,iv:pzxTcKsdk8X1kIeSl1u/tRFq+Nfg1enknt2Otb99+pw=,tag:nvOEX4YJBBa520mDoJUpIg==,type:str]
        ipv4: ENC[AES256_GCM,data:DwULulQTdRQJxw==,iv:xPkBb8HV+qTpGeFktAf9R0b0wpTUpOQyNjSZ9auRxNI=,tag:gFgd3B1px0BQAW7xnhhzbQ==,type:str]
        iid: ENC[AES256_GCM,data:8RCdQVqsLfs=,iv:hFvJJrU50r6JIgL69WD12H65uVxeaGVn/1yS4677XeQ=,tag:x204+G25eBjbW+TR3DZJDQ==,type:str]
    frrdev:
        mac: ENC[AES256_GCM,data:TAJgi2gcgk7yMZ9Dsl1kcg8=,iv:25QyzUhV6bzCo5HflojiEGbJYniGVO2KzLy+BZdT7hc=,tag:4/qlld/yoGY69e85KvRicQ==,type:str]
        ipv4: ENC[AES256_GCM,data:XVk2Q+ly8IlLqQ==,iv:jNPeNTPO2rWYoAO1hDE+iOZc4E1CfX30OFs/8BDn6ok=,tag:dk3POC5x1fk5XwttdmVmZQ==,type:str]
        iid: ENC[AES256_GCM,data:Or3d00mD2Go=,iv:n0iqyw1nZnjP+wCcnemX95sY1xCqU9rihv/PTolbFCI=,tag:erTzH8lWNv8lNM/SB86V/w==,type:str]
    monitnerr-1:
        mac: ENC[AES256_GCM,data:rbPwrXhezP1x8mHp8f0bCIY=,iv:Og1BdiKV8LB+/e9Bzr9yLvyXHfjWM2FXHr1gB35cd0k=,tag:MEc5INpdP/MTIInYFGj2eg==,type:str]
        ipv4: ENC[AES256_GCM,data:cIaeb9Sg6liIGYY=,iv:+GXNV7FORaih4muYy4Bs5XnW3FKWzis0aizmkD38klU=,tag:xgDZqcKVFSFTNkJ8lCyJFA==,type:str]
        iid: ENC[AES256_GCM,data:JEX08LmIDj6F95xEYJj1K5Tu5Q==,iv:lDHEWGVVWbEsrsiJvUD/BHzC2y+FV3CDUcdHHZEi/Xs=,tag:HTEtlOG5YpNGQ6FKG7YjWQ==,type:str]
    quicdev:
        mac: ENC[AES256_GCM,data:MMafe/uODCnQdTLkUBWLgaQ=,iv:wZQItr+ln7+Hfe+lPZQOzNdR0CaHSzWwfvRWBxuJM5U=,tag:OQtE2JQ7n27kyTufDJf7rw==,type:str]
        ipv4: ENC[AES256_GCM,data:YrYC5OZD8hR9bg==,iv:dQEkvXPq/FUNK3cQ17X9xIs00JoXvlHQ0FGlfilaZT4=,tag:srojAcXjmMFikNBlgrG86w==,type:str]
        iid: ENC[AES256_GCM,data:UeUiKfsc5Xo=,iv:52UVvhXzaEYtvk6zqCGYIawDTyvnai5t25eq6rGUYh8=,tag:qnOWgcvsfWGKuokd+4Btiw==,type:str]
    homadev:
        mac: ENC[AES256_GCM,data:76q9qKWV2ezEIPA1xcI+xo4=,iv:6YF/NqlYrVAAA85aI6VUa+GaDdFH1IoYDe665VLymYQ=,tag:APokv048OAsf0JyVeZbE+w==,type:str]
        ipv4: ENC[AES256_GCM,data:oMvI/gKyuAB8Hw==,iv:pCCF04i1Vp8kfUFEYA55LKs7fxw0jqwXXWG89gKTaoM=,tag:QOwOk+joUpi690Zo0KevbQ==,type:str]
        iid: ENC[AES256_GCM,data:FUSvgyguVAI=,iv:VHnQPPfSRRFgmmOX2tmHCoFFcVTkZm+zY522RQj1NmY=,tag:G1xY/dppQ+5+aL2SEO4OkA==,type:str]
private_zones: ENC[AES256_GCM,data:5c9WO6bW3t6KkWKyoqjOmkQGiGvNHa/pxaVj40+RGQYoAh8JQmC9y+5CBhmJ2h3shAEWzxkbq4c=,iv:MwUOBN/iNqK5hFO5mtjTMNeacFvmpHJeBIxqAfVJHNQ=,tag:VQlsmVQFpwRRUiWdg8HVGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eW1RN0dOd3RnMlZlclQr
            VXZJZnFiWE9NT2RMMGUvOVBuTjNtcGlKVkEwCmZsRk9PQU5LN1A0a2t5dlI5WWtM
            WHlLUFpHRGZjZmxkUDFjOHVoRTJ1WjAKLS0tIFdlUERXZS8yQzIwcXRhK1luaXJE
            WmdtNzk4djhDYWtJR0o2ZTkzOXhFVGsKdr7aovC0/1CsEDnEC1HB2U/AcobJV70f
            f/dAQdSv+JQmm3Rv3lfFvOdb2aQJC6l0tkh5JAm748f9Ris0kzyDYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136z4kwkfsqlvaa7e6f5c79rzjstg4ktq2lw6zadv23c038jnafssp2mngs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoazdRbmhkdzMwd3J6a0pp
            eUJjN2FOWVg1VlFhZ1Fpc2tFSUp5QjZ3OUdZClZVb0RZSmFVTDVzQm9SYWFFN1o4
            VTgybCs2WStUY3RlT3NQcXlVUkNBd0EKLS0tIEZLa1dVdGdaTUFUZFJqbE9QUmNy
            U09OcWd1RzBhK1k1TWdydEFJanlTOEUKSO6KQoPnImnH4ueUmmvNIzX1oi2f3+Sa
            DJs3AvXSn4W8c1JybxUUgRbZCuP7ndmB2A0CbmY9tnabJNaXKS6Shw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1szssulmqnc0n650xcqvn7rpu2zjwnhrta4tvcm7tpxtmg26lsqysna0fks
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN2dGd3lRYks5bFpDZ05S
            SEU1SkVjdGg0a01xZWN0ZGJxV08xR1B5Y1JjCmRjT2RkSm83RHgxUmdMZUNuSUE1
            ZkhnRGhTb0J3NmFTWmE2MkdCMGZlZk0KLS0tIEcxcjA2SnhNbDZmSXE1aktjT0Fp
            WHFvdkdqSCtVY2tsamh6VmhnQ1lCN2cKmU6R5dHb/+PBt1N/PTnPk86sglXSX1bx
            mskaISbmlf+ER+C94tVilFbV7lMdmlqaunQa8vZpHf7LTysN0WgbQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15k9ztajdwg8w98t297pml8zq0x37mm5wd85vhxvyqul6zmfpygvsl7akg6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUmovb0t4S1BiM0UvZ0wv
            UGs2N1REbnQ5anJ2bXlXblhlQVZDbzNkSTFZCmtteHhGYzkwY3IrTERwSG43YnlS
            bTFqMHpFelNSOHlQUFVtQ3FFZldOekkKLS0tIDlKSFUzSUlpRmxqK00yWkJrRUFO
            cWZ4c0xlVnN3aHljRk1NdlZHT09xa1UKFYLtaUBHA57eECMjUyXELMcn/s82eDZ2
            RWBxNqJGeJ1uYI1CYtTkzQv8FfsPi8TwYzQKzfjghP5fFOUSRPU9RA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgxvcs9q6zr4l8udgxgnzj02rzcqy4dt9x2gz9u2k97dnhj88pvqlhlvk8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOFVVblJrZkF0enUwc1Fs
            ZFNUNjlQRm43cS9aWEhOVVpnYnpCcHV6NlhBClJRUHJBc29wM1VuS2pHMFU2ZGo4
            a3VQckw3bWdJZklYamRhMzJVREJvcm8KLS0tIGVvMmprRVhEWEkxMGNaaW1NSHBq
            eWY2VVd6WWttVFVqaC96N0ljSTdGZm8KlpeQ//CyD/JQl97aBPz//p8s3rne6hqo
            eC+cfGqCiXbUi+76fz9iPtCoZozB0+6RfClEqaLIte6xSBYiz55DoA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dt4928w6c2py0rzcnwntdr6dcf62mf8wkhe3hm8mnscqxcewrdkqz6jh3d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBKzBuaWpWWXR4aVdaeGMv
            M3o4U3AxUi8veVgxRXp4eG9xTUNrSW5PS2hZCjhhbC8rV3QyUXZDS0RPRXd0dGNY
            TldLV0kvQ0dZbDFXU1lITUJiUW9PYVUKLS0tIFZwbXVSeXdGbVlLRGdJZEZEd2ZN
            QkdoenBJYkRCMloxQkdsNGk4cHFpT0UKAfr6DIAbAC4Cx/mXvt/aITAd4H6ivODa
            boRCHAxFY9fSzdDUxigorX9tJIXu9lDWGGuDM3417ksRwATNpkKtNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1323pt5w9df0ealmd0xy954ajy5gtrhvdlh4nf3d4pjqvnvvqfq3qjf5lpa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcDdCdUhNWW1hZmIxRWxt
            MkNObnRudE9uWURaK0RJWVpWMXZuTGFGMUZFCnJBNGw4VUhVTk5Zb255MktWeDgx
            bWlydklsOGNKdGxOZkQwdUUxKzE2V0UKLS0tIGpIaTFkMW1nRCtqVTFidWNkNFBO
            RHZBdUpucnJlWGFFOHRFb0pOYjFhVlkKCwW2A6MM3hwZJ7E7275X+VyPkexxiKqy
            ZYtQYLtPXRdIM5K+0SaOZBUhk7qQLsLVhr5PBNRoAsEYbzYJ0Aio+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rf9xq9wuqcvtr9u7g4vd80ck0us2nfqc3f8uey0gafsvqxf73grqcjtkfk
    lastmodified: "2026-09-22T21:26:29Z"
    mac: ENC[AES256_GCM,data:rcrFeeUPDmY77LzF5GlDLM7GXXo0T5XWy9b7D/zmflYusxzRqyFeueJ6NDTwYf8njBo5EH5zQbUZK4IJI5vQhzwj9W+F3iIHMooewQ9o/P8ezyBFO7Wr+6wW926Cwxq83NtFIq1FyZgLbftLHVaeEVpvMreze9anhtMO0FevdWs=,iv:PwhRdiVRQvs8rsneEEQj4T4qojTrohxlcvZpiCk5trc=,tag:el+93WfBO4Sw3xyCC8yGSg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
