hosts:
    living-room-hue-hub:
        mac: ENC[AES256_GCM,data:hfuAiWAPLbKuviqy4CmobeU=,iv:hkpeH+fzNx6fxg4zH8E3fOBxWDF9DIYP2HGaRO0C6BU=,tag:3MyfUf1gawW7ShA725LDGQ==,type:str]
        ipv4: ENC[AES256_GCM,data:wm1tigbWNFOaew==,iv:vkPnlKaRW+oIo5LYzgI4sGtylBUo07o150OMbAyqZqA=,tag:WVr3U4ImFq42iDCWPdSrvg==,type:str]
        iid: ENC[AES256_GCM,data:48iO93PyJmRxHjj621Opa9J9zw==,iv:z9Ri47SUMDggt5ILs/Q0RBAt40Em7pDSp8zyAsk3EVI=,tag:KVVBGXGRGika9uSqvnBupQ==,type:str]
    living-room-myq-hub:
        mac: ENC[AES256_GCM,data:6TXmbzPgt6UD8370JG3AteU=,iv:qiY1tELK52BfYUBZT3ds/YmGTyCgSGj9pYIcEyW+xds=,tag:4xvNQXDLWORiqEb9ssr+ig==,type:str]
        ipv4: ENC[AES256_GCM,data:vXMghlqTC9KacQ==,iv:zNYq2xwlhF+dKMCAhh9Tj3cd3GyebG1+dOkFZ8YRxZY=,tag:p/DVECONriZqVtOLmUhgaw==,type:str]
    office-printer:
        mac: ENC[AES256_GCM,data:m+3Dg0Cj0yMi/T+aRVO5wRY=,iv:ZnibnEVIYslkhb70zVvo4sh826hy0K/XDDBAWhL5Wa4=,tag:D6aK9fsE9vQEQcPb8oVSuw==,type:str]
        ipv4: ENC[AES256_GCM,data:jThucPjXAvu6iQ==,iv:2Ff+oFqIb0LtesBqW2cK5+jOpoB81gggjYzDs8rxn8E=,tag:cx/+b2/VorHaGNDRWkZACw==,type:str]
    prusa-core-one:
        mac: ENC[AES256_GCM,data:+L6pkdkly8mSLq5BctS8Xnw=,iv:qmtyWSPOOkPJGJ+33pxicIWvcTte/anMBXTjPNYMNDA=,tag:uZ/B4GocsbOOVKogoc+0mw==,type:str]
        ipv4: ENC[AES256_GCM,data:+XXC2z36XL8etMM=,iv:MVYKrKjzTJ/wVdvDvr/wxjzSSru8YswWa73gQdu6ksE=,tag:gzUM5JgH41hj4l8ONuxuYQ==,type:str]
        iid: ENC[AES256_GCM,data:VA/D0VplZvWBFtEqzPkSosdJ/g==,iv:WpqjWnN0RWAhicXJwb3otwvfER7i/odjvM5EgHY6X7U=,tag:d84yPuk5ow/rdEkzufN7yg==,type:str]
    psframework:
        mac: ENC[AES256_GCM,data:pQ7EeuiM66nzsNI0qgCLywM=,iv:eU40b+7VWM6H6de4Ry6HW+rLQkqKp5e/DTojfVXIp0o=,tag:uAaNBO0AjjIgcKF8goiyYg==,type:str]
        ipv4: ENC[AES256_GCM,data:Kx0UdHScHpf37w==,iv:g1Y29JlZJ68+DbNeoiOfs1XtGZwlOo/Shj8fy/t46SQ=,tag:1CsEhNVrpUnGsymgJRzB/Q==,type:str]
        iid: ENC[AES256_GCM,data:IhGnFjwbcTbBOCGdupt4wJqmoA==,iv:La0CpnxybHgHxvdf6C/Hg8pHSW7f4BlPRjr0YWihdi8=,tag:qypfvuP2wD9ZSJO31KYjYw==,type:str]
    theatnerr-2:
        mac: ENC[AES256_GCM,data:43H9UURh7/gQDMl8fCWYrFs=,iv:Ultl7rPVwTBQzvx1016C1qSaM3o344svcDAJSGPcwng=,tag:kSvl8VAw+9EhnbQFBWuovg==,type:str]
        ipv4: ENC[AES256_GCM,data:uqZXyECq8k4drA==,iv:wmgpFn8Mv6WfUG06vT9p+weZs07fpdpM0LknTH19d6A=,tag:IGmK6GMsNTAZcuIOSp0GXQ==,type:str]
        iid: ENC[AES256_GCM,data:45+T+2sTJ6welvHS5X/8ibJQ,iv:TgV08yoVXN6ZLLv0VnHWLWtDLPjVxxBE2oomBNlT/34=,tag:3sI8HpoxtxTINLAJcRPYVQ==,type:str]
    servnerr-4:
        mac: ENC[AES256_GCM,data:60LTGtvDifexlt09zpOTKw4=,iv:fGi2JjIurMzfkgoa+w1+D0Ly3rEMrY0dfvl6FqN67lk=,tag:syP5wkMEaHxhxCKINzCz+w==,type:str]
        ipv4: ENC[AES256_GCM,data:+hDRfuN37tnV,iv:ctQh0xxj8xWDGG0bONxUNUYoRS+V0CaRvnfJq0+yW8c=,tag:f5+hvYCxROLix/nV5A5CWQ==,type:str]
        iid: ENC[AES256_GCM,data:kHNyzTL1+jc=,iv:zEhcImiV7QOdN6giOkoJstUCuVYTPbyF9vfeRdy6YdU=,tag:5hPQt7xNV7MaqtPbKs2z7A==,type:str]
    nerr-4:
        mac: ENC[AES256_GCM,data:8mlnewaY7OoQK7SAnyzaSC0=,iv:DVYib3VsaTTW8lPv1uN0Y5GtquJXMTX367fv23b3KDQ=,tag:Xaj9YwzhCnvyTcY3q3CJ0A==,type:str]
        ipv4: ENC[AES256_GCM,data:sDkbHj9ueHk=,iv:Y2rZvrdR0aLjmHNEPRRnBQIO9Zu+WKyWreRujANiKhM=,tag:bnWb2QYp7KoDTYxqIdwbHw==,type:str]
        iid: ENC[AES256_GCM,data:W7mDyu8Iyp3QA+duc3pEclZ0Fw==,iv:l9pR2wO/jeVRTFpRXZXUv1Kzi31j7Pn6iHuyIIYnrWY=,tag:u74kirENzd3yPt2FFH54uw==,type:str]
    switch-core:
        mac: ENC[AES256_GCM,data:bJJ+F92sETIW7TB9Uh/iTIY=,iv:KNiYVBRO3Z8gsr0WE8KyrIQdVtZIH4QSbWGPFao75qw=,tag:YzT+m7F10v1rC+hYRjXU9A==,type:str]
        ipv4: ENC[AES256_GCM,data:am9uCN0ZQ20=,iv:71FHBpMc7uUDUI1RuQE79OuXxzkXTKWjeSissZyUNfI=,tag:tPkkfkBdwZemYzn3D4KdZA==,type:str]
        iid: ENC[AES256_GCM,data:29Af4nVC5S/c/mhDnpEoo+hAYQ==,iv:7HD3J7p0DThTZMtA/1gmPaPltHhRbWgMX9iWe8qcFNE=,tag:ESlN0Sq0yUi6jcucitPqfA==,type:str]
    switch-livingroom:
        mac: ENC[AES256_GCM,data:LMWGy4SpUj/bmAw6BdwHr4o=,iv:WdRnt/aqOG1TN4eozmHw1TIRO/HgfDnLCnMegVHrnBk=,tag:G6SB9H5NJV9SgEopg2/bEQ==,type:str]
        ipv4: ENC[AES256_GCM,data:bAQgpjg/Vjc=,iv:9VJXVs9b/Om+KJiNQ5Rk4ViAZ9XojqTsOAGOwlcYQz4=,tag:/vBantGQA2y6nhtKF6G+LA==,type:str]
        iid: ENC[AES256_GCM,data:DINZAbF+aUrhm1oUvYHgNhk+,iv:7TytCdbBQ0w/DtvOX1rMx6LDRXxcRsf71cyRRZJGL1Y=,tag:HGwkhw9b/eDgywlFG4L+pA==,type:str]
    pdu01:
        mac: ENC[AES256_GCM,data:a26xGDnTICTOxoUmvxdAIro=,iv:5+4Pf2fM2FJ1n2WJKwEG6WLvQrs7clEFBJj+3aa/nJc=,tag:/0gK8oruITUMZOx25nTi+w==,type:str]
        ipv4: ENC[AES256_GCM,data:6BrS1F0+wyw=,iv:3dc7e9mEbkZnmGikgrYBYCJV+r4a7Ujn3SPe4TRk67w=,tag:msOWivnhIDXhDDeSRXzO8g==,type:str]
    ap-livingroom:
        mac: ENC[AES256_GCM,data:hb96HaengZHVdGfZMAU+9Sg=,iv:Skx/lwGoMMSA0MFazlqJkh88lc9Ccvb3iwkOhkQ5viQ=,tag:otfCvWZCd2QTJ3nETtTSlg==,type:str]
        ipv4: ENC[AES256_GCM,data:7CxhxXIx5Qw=,iv:gSV9ogtjglxophOqL+jwOsMY2w9bc/zjJDRqwHrRes4=,tag:GOB9x+52hVG2qdwpmwdmMA==,type:str]
    ap-basement:
        mac: ENC[AES256_GCM,data:Ce8Qx2jXGvKu6VAK7EgMJrs=,iv:aq9yxJBhiATzLbWErNVDd1EDuptbJ+b90Te3qMamP9A=,tag:kdoEQkhbz1MKiHkyJOdBsg==,type:str]
        ipv4: ENC[AES256_GCM,data:GPfNIXrQYrQ=,iv:5eHJRaXCnCEJ17kJbEepZGnl54G33Pc1CVchqkZJ+Tw=,tag:v1qgwx1nc70LvBrsKojhgw==,type:str]
    ap-laundry:
        mac: ENC[AES256_GCM,data:fOCyQIhaRWzYwbr8ELvxflg=,iv:M79BtZw0N2HHe1fjbB1u5ki6QVR3uSMwUukKBTP4a7o=,tag:TYfKehduZG0jyE/P4ZPK0w==,type:str]
        ipv4: ENC[AES256_GCM,data:D07hjqDSsgI=,iv:YEiY5CBNKrgoehQQ6Xuqh32VCU9sytU4s2+9GTNlxik=,tag:onF9Kzo25vaTySzk2svIHQ==,type:str]
    ups01:
        mac: ENC[AES256_GCM,data:mzwXMqDaf6qmVqSskfpxlCk=,iv:+rO+WzoH6hn+7EweVAQtNjGv3tkvbJl2Dd3wYwEgjX4=,tag:boQVaT+xN4l2+9JQTZiPFg==,type:str]
        ipv4: ENC[AES256_GCM,data:IIXELsIYAts5,iv:a5/Z09uOtlJf4o9rM5d+HjReHuMPQhKhq3jg/U2n0sk=,tag:v+s3XxQHP7w09t/rhBhmWA==,type:str]
    hass:
        mac: ENC[AES256_GCM,data:enEPXoX0QpCNTHGJ5DITJ1w=,iv:OBy/ivwqiHmIrXopRazmjRGPWaRiqPjAgvIFrnI8S1E=,tag:M089Ye+SDphcfGUCMtgFHg==,type:str]
        ipv4: ENC[AES256_GCM,data:mJ3RgUFpHRaj,iv:QKuHvCRHjNVAZsH27e0CR0g41Qsp6QKAJrCxMpyvPhA=,tag:C2hu254DOfUfl4ois5MU4A==,type:str]
        iid_ula: ENC[AES256_GCM,data:fKDR5jyi1IBpF7Ru8xikXDRVeQ==,iv:QoRzhIUmT7qVs4COaiaoR8rmkYB0s3ZIpqHoCLWvWLM=,tag:JPDUM6XNZBhmlCR7qUzU6g==,type:str]
    linuxdev:
        mac: ENC[AES256_GCM,data:ejquyCNlfbUvrNxsJKD356s=,iv:pzxTcKsdk8X1kIeSl1u/tRFq+Nfg1enknt2Otb99+pw=,tag:nvOEX4YJBBa520mDoJUpIg==,type:str]
        ipv4: ENC[AES256_GCM,data:DwULulQTdRQJxw==,iv:xPkBb8HV+qTpGeFktAf9R0b0wpTUpOQyNjSZ9auRxNI=,tag:gFgd3B1px0BQAW7xnhhzbQ==,type:str]
        iid: ENC[AES256_GCM,data:8RCdQVqsLfs=,iv:hFvJJrU50r6JIgL69WD12H65uVxeaGVn/1yS4677XeQ=,tag:x204+G25eBjbW+TR3DZJDQ==,type:str]
    frrdev:
        mac: ENC[AES256_GCM,data:TAJgi2gcgk7yMZ9Dsl1kcg8=,iv:25QyzUhV6bzCo5HflojiEGbJYniGVO2KzLy+BZdT7hc=,tag:4/qlld/yoGY69e85KvRicQ==,type:str]
        ipv4: ENC[AES256_GCM,data:XVk2Q+ly8IlLqQ==,iv:jNPeNTPO2rWYoAO1hDE+iOZc4E1CfX30OFs/8BDn6ok=,tag:dk3POC5x1fk5XwttdmVmZQ==,type:str]
        iid: ENC[AES256_GCM,data:Or3d00mD2Go=,iv:n0iqyw1nZnjP+wCcnemX95sY1xCqU9rihv/PTolbFCI=,tag:erTzH8lWNv8lNM/SB86V/w==,type:str]
    quicdev:
        mac: ENC[AES256_GCM,data:MMafe/uODCnQdTLkUBWLgaQ=,iv:wZQItr+ln7+Hfe+lPZQOzNdR0CaHSzWwfvRWBxuJM5U=,tag:OQtE2JQ7n27kyTufDJf7rw==,type:str]
        ipv4: ENC[AES256_GCM,data:YrYC5OZD8hR9bg==,iv:dQEkvXPq/FUNK3cQ17X9xIs00JoXvlHQ0FGlfilaZT4=,tag:srojAcXjmMFikNBlgrG86w==,type:str]
        iid: ENC[AES256_GCM,data:UeUiKfsc5Xo=,iv:52UVvhXzaEYtvk6zqCGYIawDTyvnai5t25eq6rGUYh8=,tag:qnOWgcvsfWGKuokd+4Btiw==,type:str]
    homadev:
        mac: ENC[AES256_GCM,data:76q9qKWV2ezEIPA1xcI+xo4=,iv:6YF/NqlYrVAAA85aI6VUa+GaDdFH1IoYDe665VLymYQ=,tag:APokv048OAsf0JyVeZbE+w==,type:str]
        ipv4: ENC[AES256_GCM,data:oMvI/gKyuAB8Hw==,iv:pCCF04i1Vp8kfUFEYA55LKs7fxw0jqwXXWG89gKTaoM=,tag:QOwOk+joUpi690Zo0KevbQ==,type:str]
        iid: ENC[AES256_GCM,data:FUSvgyguVAI=,iv:VHnQPPfSRRFgmmOX2tmHCoFFcVTkZm+zY522RQj1NmY=,tag:G1xY/dppQ+5+aL2SEO4OkA==,type:str]
    pikvm:
        mac: ENC[AES256_GCM,data:Fx4V3I57teepMP5e+H9Sr+c=,iv:a8OHDzAhk6ez0xGAyH8J07eDmJHJgXo3E841cYPvyjU=,tag:iBtTmYpJVwI++7koAmQ0fg==,type:str]
        ipv4: ENC[AES256_GCM,data:l2aSKRleq6jq,iv:16siuksuNNpnDGW8uyBmp4AJ1GK20bcDJxxG5IRL908=,tag:yTO2gMEMKuW+WpxSBP150A==,type:str]
        iid: ENC[AES256_GCM,data:Qr3w0c6sQypjkl2fmC0eIFdauQ==,iv:Q1ooKxebwFhZSHbhuR8C2QsClbQ2YtyfXr9CatF65/s=,tag:Vnee+w9DhRfAdemGC9Y5Pw==,type:str]
    gamnerr-1:
        mac: ENC[AES256_GCM,data:i3DE1PphjoJYl7+CfJFn5Ec=,iv:lFZS9/mM3ER7Hc0N+rUPcAqLcEEx4/94A34e+2FubgY=,tag:u8kRZrfIksysENFnIisKNA==,type:str]
        ipv4: ENC[AES256_GCM,data:zxQbK+53v3XA,iv:jkR01cyb0S4cJwix57CrGdUR1hL3/e2RGglGbhdauhs=,tag:oEDT0fYnqYs+0pvgRcOYYA==,type:str]
        iid: ENC[AES256_GCM,data:2gVxmXbn0FrcCFi8bV3GDuMYRA==,iv:SyNvPcMDnMa86wCTZiuJXivu5+guL8OmxCMltk7h/Jk=,tag:+3ZEAhTOqbrzEnwi3KLuWA==,type:str]
    office-lgc4:
        mac: ENC[AES256_GCM,data:WhT0K35zZUiPBxHe3Tc9+yU=,iv:VXVOUcsoWig57Q/n5YwCFbGTFwaJtg6/2RwusPXd9zQ=,tag:LalqtkPh02QbJNFA8bJv8w==,type:str]
        ipv4: ENC[AES256_GCM,data:kn3gnBhAaYLwuA==,iv:uRHloNHMBjpWdwQVDeFnrj3lEp/2eGoXLTwdDWwfCpM=,tag:yy97v0dRykIXmfuFBzKK8A==,type:str]
        iid: ENC[AES256_GCM,data:/ru26E8PokSxOFv8RMuHPBIuyw==,iv:yhjnAda0RYRYsHR/AF/I1eZyKABYHkhrxEuW8SNzf5E=,tag:HMmsugB2YOwpst9UaLJSbA==,type:str]
private_zones: ENC[AES256_GCM,data:5c9WO6bW3t6KkWKyoqjOmkQGiGvNHa/pxaVj40+RGQYoAh8JQmC9y+5CBhmJ2h3shAEWzxkbq4c=,iv:MwUOBN/iNqK5hFO5mtjTMNeacFvmpHJeBIxqAfVJHNQ=,tag:VQlsmVQFpwRRUiWdg8HVGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnaVhQTXNZK0xNQ1A0VmMz
            Zi92WHQ5TU1LZDVDL0psTkJGVHJxSVNiWENZCjl5SVRLbEY3Y1RoTEZiSGFoWkJI
            N2ZUakRzTklVKzU4NlpXejFlVnk2dFUKLS0tIExaV2d2SU1zTUR5YmhZb1FrRlVN
            aEc1Q3JKblU4RzhnZ3lsenUvbEttV0UKNWROBNSr+rXsTD7mNCTAcdQsrvtB6kMY
            3/i1RJVtDh9KAy4/BscqPxsSbtEmpcGdd8JcX0AqNkp7UuP9RlZ6mA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136z4kwkfsqlvaa7e6f5c79rzjstg4ktq2lw6zadv23c038jnafssp2mngs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcWx4K04zKzA4b0wxQTh4
            bllQbWp3a2luRkxuYmFESW1GakV0S3pHZG5nCkF1Zk5Wa28vVlFBcElNSG0vMmx1
            NTZyOFExaEFnOXJIbWlpQlJFNVp2Nm8KLS0tIGRhNnRpcllQb1JQcWNxZUt3SStq
            WXdGWHdIRzhBUTBqVEpNMlJ6ZzJBN0EK9SzPTApC+uDpoIrYDh+Rt03dr0eqvxbY
            fvUDePlGOKrjNbek1dno142nPgIiNcZ41GBz4bZu1E36+m8RjgE+XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1szssulmqnc0n650xcqvn7rpu2zjwnhrta4tvcm7tpxtmg26lsqysna0fks
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVG1kZXhObkJNblpIaHZh
            SHRPS0ZDd0ZHZVlKWFZ3ZHZqRThYazhpL2s4CjlxQ2ViRXFHb2tlamc3Z2RENEJC
            ZUR3VzJzVTlJZ0t3WmFZN3ZwSVo0NDAKLS0tIFhIYno4MDhUSXFjM2pvRElvZlIy
            K0NBK1Zzd0lTSVZmVldqc29HVTJ2VmsKfeuXVF8w619RdfXQFpYJZ+l1ddHv48jo
            0yPdMvFNyReIrkmb3FLGpOncl0Ghfb5h7J4aSxx663d4VoS+5xqQmA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v6mhrhylaretpey25vyax8032vg060yrg5mrs3rz5gvstzqs2pcqsaqhzj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZKzZxWHVtWWZ0cjVPa3FT
            V1o4UGlpK3lqcU0wU1k1aFMvNFpzSVpQdHcwCnEvdW44STdtVm1CaHgvRSthbkV1
            d0d5WjdoUW9wMHdXcnl6VGkyK2VKaTQKLS0tIEtsWmwvL1ZpZW8vOVBwVE1VWm51
            bTh2dlJrV3ljbmJxZlErUzcxb1VKWDQKJ8xnelso2qmFAH+Rz2gI6FsuU5dPTNJ8
            oEp2B0AOz7GnuF1ZubbHA5JCU8DNYCRjapxmB0JTsG8SCXZ2q2KCBA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vgxvcs9q6zr4l8udgxgnzj02rzcqy4dt9x2gz9u2k97dnhj88pvqlhlvk8
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTzRXYXdjam5hdm9RTk0x
            VUFzTno4TG03U2l4cFlveXpITFVkWnJXV1E4Cjlrc3d1Y2lWMldUbFJYQ1ZiaXlJ
            L1VXeFRKbklvVXBsS05oeW44d3ZKTnMKLS0tIHZ2NjV4QktjU0RrNE0yV0lkZks1
            OCtZS01MVE1OdXh0Z2dXdU1hU3hHTmMKt2TXTx9RZPoHpXNeBvVpzUi5lC4kdZ9N
            yrZbTeptUkO1lcq9pOWwSC6F94XNjWvQebWmfk+t4XZyFHzefdhkpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dt4928w6c2py0rzcnwntdr6dcf62mf8wkhe3hm8mnscqxcewrdkqz6jh3d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RjB2R2puUXcxd01SSkhu
            ZHl1M0F0cVNOa0JKb2JxZFJ3NUQySE43cldrCldqUHFud1lvVUNwaXdCeGZKakpU
            YnI3b2VTT3dhckhmQlY5RktOaUoxYTQKLS0tIGZlY3BaRlNWWWQ5V0N0cGYxYzZK
            Y3BiVUhGY0F3RGZJZjU3bmJUYXRFWGsKiInY1v/vVcjMZ0B82/pAzt4mtzJ7t65s
            GqjrCI1/5NJaMFsTSSanSr87wD5cz2A5ICGZSh4PanBT45twlNcGAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1323pt5w9df0ealmd0xy954ajy5gtrhvdlh4nf3d4pjqvnvvqfq3qjf5lpa
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UE1PTWx1VHlZVVZLcHNy
            ODNmQUJEZWtXcDBuYzJIdHQwcGtqVkxUWXljCkNxNmM1djMwZktuc04wanZCTkZn
            S0R4bmp5c1Yva2I2R212NHFFdGd0eVUKLS0tICtEVHVTbEs0T1RtWkNLdU5YRWRq
            Mmt2MCtkZHUwOTdUOHlOS3FVemIyYlEKyxvNJkCGTLPXxMzNvUxGVpIu1z/rO85T
            q0Ir93qRR2vNYL4hUC6flD2GBRDzTIENmYTXOrfrMM7i7NZ7kMCduw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rf9xq9wuqcvtr9u7g4vd80ck0us2nfqc3f8uey0gafsvqxf73grqcjtkfk
    lastmodified: "2026-10-05T01:29:37Z"
    mac: ENC[AES256_GCM,data:pbhh9St6fRjqX/2rhFVODV8n4srzk6p7HilHgEiW8tz2KhLRGxTMbED+SxREC1r3ilNiF6qECzOwjkCfJDikUBHSXvRk7rx0jVh87FgE8Jl2JZ+gHiLR5XHN0ezQOJa0VZKOvipUZTfbLiJdsv3M1Xii7b8FZdZeV0DoqHk6/5U=,iv:Mrr8kYst927KfQvKDXlwU5O9UUrF805jIBQrQk5Jaf4=,tag:nBQygTU6O1/zDIdvAZdBvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
