{
 "title": "Network",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "WAN Bandwidth I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{ifAlias=~\"WAN|wg0\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "receive: {{ifAlias}}"
    },
    {
     "expr": "rate(ifOutOctets{ifAlias=~\"WAN|wg0\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "transmit: {{ifAlias}}"
    }
   ]
  },
  {
   "title": "WAN Packet I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInUcastPkts{ifAlias=~\"WAN|wg0\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "receive unicast: {{ifAlias}}"
    },
    {
     "expr": "rate(ifOutUcastPkts{ifAlias=~\"WAN|wg0\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "transmit unicast: {{ifAlias}}"
    }
   ]
  },
  {
   "title": "LAN Bandwidth I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{ifAlias!~\"WAN|lo|eth2|wg.*|imq.*\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "transmit: LAN to {{ifAlias}}"
    },
    {
     "expr": "rate(ifOutOctets{ifAlias!~\"WAN|lo|eth2|wg.*|imq.*\",instance=\"routnerr-1\",job=\"snmp\"}[1m])",
     "legendFormat": "receive: {{ifAlias}} from LAN"
    }
   ]
  },
  {
   "title": "Office switch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{ifAlias!=\"\",instance=\"switch-office01\",job=\"snmp\"}[1m]) and on(instance, job, ifName) ifAdminStatus != 2",
     "legendFormat": "from: {{ifAlias}}"
    },
    {
     "expr": "rate(ifOutOctets{ifAlias!=\"\",instance=\"switch-office01\",job=\"snmp\"}[1m]) and on(instance, job, ifName) ifAdminStatus != 2",
     "legendFormat": "to: {{ifAlias}}"
    }
   ]
  },
  {
   "title": "Core switch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(ifInOctets{ifAlias!=\"\",instance=\"switch-livingroom01\",job=\"snmp\"}[1m]) and on(instance, job, ifName) ifAdminStatus != 2",
     "legendFormat": "from: {{ifAlias}}"
    },
    {
     "expr": "rate(ifOutOctets{ifAlias!=\"\",instance=\"switch-livingroom01\",job=\"snmp\"}[1m]) and on(instance, job, ifName) ifAdminStatus != 2",
     "legendFormat": "to: {{ifAlias}}"
    }
   ]
  }
 ]
}