{
 "title": "Node",
 "tags": [ "node" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "node_uname_info" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$instance.*\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance.*\",device!~\"lo|docker.*|virbr.*\"}[5m]) * 8",
     "legendFormat": "receive: {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance.*\",device!~\"lo|docker.*|virbr.*\"}[5m]) * 8",
     "legendFormat": "transmit: {{device}}"
    },
    {
     "expr": "irate(wireguard_peer_receive_bytes_total{instance=~\"$instance.*\"}[5m]) * on (public_key, device) group_left(name) wireguard_peer_info * on (instance) group_left(device) wireguard_device_info",
     "legendFormat": "receive: {{device}}: {{name}}"
    },
    {
     "expr": "irate(wireguard_peer_transmit_bytes_total{instance=~\"$instance.*\"}[5m]) * on (public_key, device) group_left(name) wireguard_peer_info * on (instance) group_left(device) wireguard_device_info",
     "legendFormat": "transmit: {{device}}: {{name}}"
    }
   ]
  },
  {
   "title": "Device temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance.*\",job=\"node\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names * on (instance, chip, sensor) group_left(label) node_hwmon_sensor_label",
     "legendFormat": "{{chip_name}}: {{label}} ({{sensor}})"
    },
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"$instance.*\",job=\"node\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names{chip_name=\"drivetemp\"}",
     "legendFormat": "{{chip_name}}: {{chip}} ({{sensor}})"
    }
   ]
  },
  {
   "title": "Device power consumption",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_power_watt{instance=~\"$instance.*\",job=\"node\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names * on (instance, chip, sensor) group_left(label) node_hwmon_sensor_label",
     "legendFormat": "{{chip_name}}: {{label}} ({{sensor}})"
    },
    {
     "expr": "node_hwmon_power_average_watt{instance=~\"$instance.*\",job=\"node\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names",
     "legendFormat": "{{chip_name}}: {{sensor}} (average)"
    },
    {
     "expr": "sum by (instance, chip, chip_name) (node_hwmon_curr_amps{instance=~\"$instance.*\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names) * sum by(instance, chip, chip_name) (node_hwmon_in_volts{instance=~\"$instance.*\"} * on (instance, chip) group_left(chip_name) node_hwmon_chip_names)",
     "legendFormat": "{{chip_name}}"
    }
   ]
  },
  {
   "title": "CPU utilization in cores/second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum((irate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$instance.*\",job=\"node\"}[5m]))) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Maximum CPU frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "max(node_cpu_scaling_frequency_hertz{instance=~\"$instance.*\"})",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{instance=~\"$instance.*\",job=\"node\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$instance.*\",job=\"node\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$instance.*\",job=\"node\"} - node_memory_SwapFree_bytes{instance=~\"$instance.*\",job=\"node\"}",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_zfs_arc_size{instance=~\"$instance.*\",job=\"node\"}",
     "legendFormat": "ZFS ARC"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"$instance.*\",job=\"node\",device!~\"dm.*\"}[5m])",
     "legendFormat": "read: {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$instance.*\",job=\"node\",device!~\"dm.*\"}[5m])",
     "legendFormat": "write: {{device}}"
    }
   ]
  },
  {
   "title": "ZFS free space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$instance.*\",job=~\"node\",fstype=\"zfs\",mountpoint=\"/primary\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_free_bytes{fstype=~\"ext4|vfat\",instance=~\"$instance.*\"} / node_filesystem_size_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}