{
 "title": "OBS",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Output Activity",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "obs_output_active",
     "legendFormat": "output: {{output_id}}: {{output_name}}"
    }
   ]
  },
  {
   "title": "Microphone Output",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "obs_source_channel_magnitude{source_id=\"pulse_input_capture\"}",
     "legendFormat": "Average: {{source_name}}: channel {{channel_id}}"
    },
    {
     "expr": "obs_source_channel_peak{source_id=\"pulse_input_capture\"}",
     "legendFormat": "Peak: {{source_name}}: channel {{channel_id}}"
    }
   ]
  },
  {
   "title": "Average Frame Rendering Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "obs_global_average_frame_time_ns",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Output Frames Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "irate(obs_output_frames[5m])", "legendFormat": "{{output_id}}: {{output_name}}" }
   ]
  },
  {
   "title": "Problematic Frames Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(obs_global_lagged_frames_total[5m])",
     "legendFormat": "lagged"
    },
    {
     "expr": "irate(obs_global_video_skipped_frames_total[5m])",
     "legendFormat": "skipped"
    },
    {
     "expr": "irate(obs_output_dropped_frames_total[5m])",
     "legendFormat": "dropped: {{output_id}}: {{output_name}}"
    }
   ]
  },
  {
   "title": "Output Data Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(obs_output_bytes_total[5m]) * 8",
     "legendFormat": "{{output_id}}: {{output_name}}"
    },
    {}
   ]
  }
 ]
}