{
 "title": "wgipamd",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Time since last Purge",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - wgipamd_store_last_purge"
    }
   ]
  },
  {
   "title": "wg-dynamic Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(wgipamd_server_requests_total[1m])",
     "legendFormat": "{{interface}}: {{operation}}"
    }
   ]
  },
  {
   "title": "Subnet utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "wgipamd_store_ips_allocated / wgipamd_store_subnet_allocatable_size",
     "legendFormat": "{{subnet}}"
    }
   ]
  }
 ]
}